image: node:lts

services:
  - postgres
  

variables:
  PIPELINE: true
  POSTGRES_DB: postgres
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: wwBYwjhtwTWfK+Z+Bdb3KIq9JQxbyNDIW11vD2TRISQ

stages:
  - quality
  - test
  - build

lint:
  stage: quality 
  script:
    - npm run installs
    - npm run lint


test:
  stage: test
  services:
    - name: postgres:14
      alias: postgres
  variables:
    POSTGRES_PORT: 5432
    PGPASSWORD: wwBYwjhtwTWfK+Z+Bdb3KIq9JQxbyNDIW11vD2TRISQ
    POSTGRES_HOST: postgres
    PGHOST: postgres
    POSTGRES_DB: postgres
    POSTGRES_USER: dev
    POSTGRES_PASSWORD: wwBYwjhtwTWfK+Z+Bdb3KIq9JQxbyNDIW11vD2TRISQ
  before_script:
    - apt-get update -qq
    - apt-get install -y postgresql-client
    - until pg_isready -h postgres -U dev; do echo "Waiting for PostgreSQL..."; sleep 1; done
    - npm run installs
  script:
    - npm run build
    - psql -h postgres -U dev -d postgres -f ./microservice/AuthService/sql/databases.sql
    - psql -h postgres -U dev -d postgres -f ./microservice/PermitService/sql/databases.sql
    - psql -h postgres -U dev -d postgres -f ./microservice/TicketService/sql/databases.sql
    - psql -h postgres -U dev -d postgres -f ./microservice/VehicleService/sql/databases.sql
    - npm run test

build:
  stage: build
  script:
    - npm run installs
    - npm run build
